## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './data/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [4]:
rows_count = app_train.shape[0]
columns_count = app_train.shape[1]
print('Total rows : %s' % (rows_count))
print('Total columns : %s' % (columns_count))

Total rows : 307511
Total columns : 122

#### 列出所有欄位

In [5]:
app_train.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 截取部分資料

In [6]:
app_train[app_train['NAME_CONTRACT_TYPE'] == 'Cash loans']

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
30,100035,0,Cash loans,F,N,Y,0,292500.000,665892.0,24592.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
31,100036,0,Cash loans,F,N,Y,0,112500.000,512064.0,25033.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,5.0
32,100037,0,Cash loans,F,N,N,0,90000.000,199008.0,20893.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
33,100039,0,Cash loans,M,Y,N,1,360000.000,733315.5,39069.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
34,100040,0,Cash loans,F,N,Y,0,135000.000,1125000.0,32895.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
35,100041,0,Cash loans,F,N,N,0,112500.000,450000.0,44509.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307479,456219,0,Cash loans,F,N,Y,1,112500.000,521280.0,31630.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307480,456220,0,Cash loans,F,N,N,1,81000.000,1350000.0,39474.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
307481,456225,1,Cash loans,M,N,Y,0,225000.000,297000.0,19975.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307482,456226,0,Cash loans,F,Y,Y,0,225000.000,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307483,456227,0,Cash loans,F,N,Y,0,99000.000,247275.0,16479.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307484,456228,0,Cash loans,F,Y,N,0,540000.000,545040.0,35617.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307486,456230,0,Cash loans,F,Y,Y,1,292500.000,355536.0,18283.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307487,456231,0,Cash loans,M,N,Y,0,117000.000,1071909.0,31473.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
307488,456232,0,Cash loans,F,N,N,0,157500.000,135000.0,13351.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307489,456233,1,Cash loans,F,N,Y,0,225000.000,521280.0,23089.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
307490,456234,0,Cash loans,M,N,Y,0,81000.000,135000.0,9148.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307491,456235,0,Cash loans,M,Y,Y,2,90000.000,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307492,456236,0,Cash loans,M,Y,Y,0,585000.000,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307493,456237,0,Cash loans,F,N,Y,0,135000.000,946764.0,37678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307494,456238,0,Cash loans,M,Y,N,1,270000.000,479700.0,46858.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,0,Cash loans,M,Y,N,0,180000.000,808650.0,23773.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307497,456241,0,Cash loans,F,Y,Y,0,180000.000,270126.0,12028.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,0,Cash loans,M,Y,Y,0,198000.000,1312110.0,52168.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307499,456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
307500,456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
307501,456245,0,Cash loans,F,N,Y,3,81000.000,269550.0,11871.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307502,456246,0,Cash loans,F,N,Y,1,94500.000,225000.0,10620.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307503,456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307504,456248,0,Cash loans,F,N,Y,0,153000.000,331920.0,16096.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307505,456249,0,Cash loans,F,N,Y,0,112500.000,225000.0,22050.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
307506,456251,0,Cash loans,M,N,N,0,157500.000,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.000,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.000,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

In [10]:
app_train[(app_train['NAME_CONTRACT_TYPE'] == 'Cash loans') & (app_train['FLAG_OWN_CAR'] == 'Y') & (app_train['AMT_INCOME_TOTAL'] > 100000)]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
6,100009,0,Cash loans,F,Y,Y,1,171000.0,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.0,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
15,100019,0,Cash loans,M,Y,Y,0,157500.0,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
21,100025,0,Cash loans,F,Y,Y,1,202500.0,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
24,100029,0,Cash loans,M,Y,N,2,135000.0,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.0,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
33,100039,0,Cash loans,M,Y,N,1,360000.0,733315.5,39069.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
49,100056,0,Cash loans,M,Y,Y,0,360000.0,1506816.0,49927.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
51,100059,0,Cash loans,M,Y,Y,1,540000.0,675000.0,34596.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
58,100069,0,Cash loans,M,Y,Y,1,360000.0,640458.0,27265.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
59,100070,0,Cash loans,M,Y,Y,0,540000.0,1227901.5,46899.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
62,100073,0,Cash loans,M,Y,Y,0,324000.0,1130760.0,40189.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
64,100076,0,Cash loans,M,Y,N,0,180000.0,315000.0,9679.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
66,100078,0,Cash loans,F,Y,Y,0,180000.0,1035000.0,43983.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
69,100081,0,Cash loans,M,Y,N,0,180000.0,450000.0,21109.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
71,100083,0,Cash loans,M,Y,Y,0,103500.0,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
82,100097,0,Cash loans,M,Y,Y,0,157500.0,760225.5,30280.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0
85,100100,0,Cash loans,M,Y,Y,2,202500.0,796396.5,38443.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
86,100101,0,Cash loans,F,Y,Y,0,202500.0,343377.0,22072.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
92,100110,0,Cash loans,M,Y,Y,3,135000.0,373140.0,25065.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
93,100111,0,Cash loans,F,Y,N,1,112500.0,862560.0,27954.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
94,100112,1,Cash loans,M,Y,Y,0,315000.0,953460.0,64107.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
116,100136,0,Cash loans,M,Y,N,1,157500.0,1571931.0,49356.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
117,100137,0,Cash loans,F,Y,Y,0,225000.0,891072.0,45625.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
118,100138,0,Cash loans,M,Y,N,0,135000.0,824823.0,29223.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
121,100142,0,Cash loans,M,Y,Y,1,360000.0,579195.0,27994.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
124,100145,0,Cash loans,F,Y,Y,1,202500.0,260725.5,16789.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
125,100146,0,Cash loans,M,Y,Y,0,117000.0,327024.0,12456.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
128,100149,0,Cash loans,M,Y,N,0,171000.0,539590.5,26374.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307371,456096,0,Cash loans,F,Y,Y,0,112500.0,728460.0,39676.5,...,0,0,0,0,0.0,0.0,1.0,0.0,2.0,0.0
307374,456099,0,Cash loans,M,Y,Y,0,270000.0,1042560.0,66757.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307380,456105,0,Cash loans,M,Y,N,0,225000.0,1005120.0,29389.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
307382,456107,0,Cash loans,M,Y,Y,1,225000.0,1437799.5,42169.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307393,456126,0,Cash loans,F,Y,Y,0,202500.0,544500.0,15921.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
307397,456130,0,Cash loans,F,Y,Y,0,202500.0,753840.0,22171.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307401,456134,0,Cash loans,F,Y,Y,0,135000.0,1718473.5,47385.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307407,456140,1,Cash loans,F,Y,Y,1,261000.0,711454.5,47673.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
307408,456141,0,Cash loans,F,Y,Y,1,112500.0,237024.0,18855.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307415,456148,0,Cash loans,M,Y,Y,0,180000.0,589045.5,30204.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307421,456154,0,Cash loans,M,Y,Y,0,157500.0,144000.0,9751.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307427,456160,0,Cash loans,F,Y,Y,0,270000.0,1298970.0,46786.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307435,456173,0,Cash loans,M,Y,Y,0,189000.0,675000.0,19737.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307442,456180,0,Cash loans,M,Y,Y,1,135000.0,90000.0,9580.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307445,456183,0,Cash loans,F,Y,Y,0,180000.0,990000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307449,456187,0,Cash loans,M,Y,Y,1,315000.0,1175314.5,38974.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307451,456190,0,Cash loans,M,Y,N,1,450000.0,545040.0,25407.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307452,456191,0,Cash loans,F,Y,N,2,153000.0,1350000.0,46926.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0
307459,456198,0,Cash loans,M,Y,Y,0,225000.0,959017.5,49095.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307460,456199,0,Cash loans,M,Y,N,1,382500.0,745429.5,24354.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
307462,456201,0,Cash loans,F,Y,Y,3,135000.0,1024785.0,57222.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307474,456214,0,Cash loans,M,Y,Y,2,135000.0,360000.0,23004.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307482,456226,0,Cash loans,F,Y,Y,0,225000.0,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307484,456228,0,Cash loans,F,Y,N,0,540000.0,545040.0,35617.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307486,456230,0,Cash loans,F,Y,Y,1,292500.0,355536.0,18283.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307492,456236,0,Cash loans,M,Y,Y,0,585000.0,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307494,456238,0,Cash loans,M,Y,N,1,270000.0,479700.0,46858.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,0,Cash loans,M,Y,N,0,180000.0,808650.0,23773.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307497,456241,0,Cash loans,F,Y,Y,0,180000.0,270126.0,12028.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,0,Cash loans,M,Y,Y,0,198000.0,1312110.0,52168.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0